version: '3'
services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: sql-server
    image: microsoft/mssql-server-linux:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "[STRONG_PASSWORD]"
      ACCEPT_EULA: "Y"
    restart: always
    volumes: 
      - sql-server:/var/opt/mssql/data
volumes:
  sql-server: