version: '3'

services:
  drupal:
    image: drupal:latest
    ports:
      - '8080:80'
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_PASSWORD: example

    
